repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: npm-format-check
        name: Run prettier on TypeScript sources
        entry: npm run format-check
        language: system
        pass_filenames: false
      - id: npm-lint
        name: Run eslint on source files
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: npm-test
        name: Run unit tests
        entry: npm test -- --runInBand
        language: system
        pass_filenames: false
        stages: [pre-push]
